### ISSUE TITLE
[Playtime ends] Create UI for the user to explore more science-backed info related to activity 

### ISSUE THREAD

**Issue by saramakishti** [amosproj/amos2024ws04-personalized-play#106]
### Purpose

In order to allow user to explore science behind the playtime session

### User Story

As a user, I want the app to provide an option to explore science behind playtime session so that I can learn about how this playtime session helped in my child's growth.

### Acceptance criteria

- [ ] When the user clicks on the Explore Science icon, the app will display a new screen with the heading, "How this session has helped in your child's growth?"
- [ ] Below that, there will be a list of all the skills that the user selected at the time of starting this playtime.
- [ ] The screen will also have "done" button at bottom
- [ ] When the user clicks on the "done" button, the user will be directed to the home screen.

### Design notes

* Wireframes are [here](https://app.visily.ai/projects/c005caa3-974a-4e5b-be6c-2b00e5b6645b/boards/1382078)

* Design specifics are [here](https://app.visily.ai/projects/c005caa3-974a-4e5b-be6c-2b00e5b6645b/boards/1436412)

---

### Definition of Done (DoD)

- [ ] The feature has been fully implemented, thoroughly tested, and integrated into the app with no critical bugs or performance issues.
- [ ] Manual testing is complete, verifying that the feature meets all acceptance criteria.
- [ ] Big features are documented inside the code, with clear explanations of functionality, usage, and any relevant edge cases.
- [ ] The feature has undergone peer review, with the code approved by at least one other team member to ensure quality and maintainability.
- [ ] The feature branch has been successfully merged into the main branch, and the pull request is closed and the branch is deleted.
- [ ] The feature’s UI/UX has been reviewed to ensure consistency and alignment with design guidelines.

**Comment by shanaka95** [comment]
https://github.com/user-attachments/assets/c3df696d-e34a-4105-9dfd-93c02d9cac16

**Comment by shanaka95** [comment]
https://github.com/user-attachments/assets/a0d9731e-f6d6-4776-b565-10abd0468cee
