### ISSUE TITLE
[Onboarding flow] Get contextual questions from user - {no. of kids}

### ISSUE THREAD

**Issue by Rushi-faldu** [amosproj/amos2024ws04-personalized-play#18]
### Purpose

We need to ask the user (parent) a few questions in order to save them in the app context before suggesting a playtime activity.

### User Story

As a user (parent), I want to give a few personal contextual answers that will be saved during my quick onboarding, so that I can get a personalized play activity suggestion.

### Acceptance Criteria

- The app prompts the user to answer how many kids are there with him/her.
- The user (parent) will have to type in the number of kids as an input.
     - The happy path for now is to assume the parent has only 1 kid so the user will input 1. 
- This parameter - number of kids - will be saved in the app context and user profile.

### Dev Notes

Use the following link as inspiration about the design: https://app.visily.ai/projects/c005caa3-974a-4e5b-be6c-2b00e5b6645b/boards/1382078

**Comment by saramakishti** [comment]
@frederickbaier Please add 'Real Estimation' field for this issue.
